### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by wafa-bouzouita** [yingkunwu/R-YOLOv4#26]
Hello,
I have a question regarding training a custom dataset.

    How can I transfer learning of some specific classes from the pre-trained weights (e.g. dota) to my custom training if my custom classes are different from the pre-trained classes?

Best regards and Thank you

**Comment by yingkunwu** [comment]
I believed if you want to transfer learning some specific classes from the pre-trained weights, your classes in your custom dataset  should be matched with the pre-trained one. However, you can try to make use of the features trained by the pre-trained weights by eliminating weights in yolo’s head before training. This is because that the dimensions of the output of the pre-trained model is not the same as yours.

Feel free to ask more questions if the above answer was not clear.
