### ISSUE TITLE
Extra classes

### ISSUE THREAD

**Issue by candyotter** [yingkunwu/R-YOLOv4#3]
Do you think it would be possible to train this on my own dataset or add extra classes to this?
What would I need to change to have more than plane and car classes?

Thank you

**Comment by yingkunwu** [comment]
Yes. First, you have to make your own dataset and label it individually. You have to make sure the format of labels is the same as the one I provided; otherwise, you have to change the code to match your format.
To train more classes the only thing you have to do is change the code in this line. (Yolo(classes=yours)) However, I can not guarantee the result would still be good or not. There are lots of reasons that could damage the result such as the integrity of datasets or the structure of the model.
https://github.com/kkkunnnnethan/R-YOLOv4/blob/4043582227f4f60eaec39cbb228b6dcbb30d7b64/train.py#L50

**Comment by candyotter** [comment]
Awesome, thank you!
